### ISSUE TITLE
Run into error when trying to use more than 1 CPU

### ISSUE THREAD

**Issue by dhhagan** [FunWithR/MonteCarlo#1]
I'm not sure if this is a dependency issue or not (quick google didn't help), but I obtain the following error when trying to run with >1 CPU:
![capture](https://cloud.githubusercontent.com/assets/4370504/25305018/5c8bbb4c-2741-11e7-98b0-494461c60892.PNG)

**Comment by FunWithR** [comment]
Are you using version 1.0.0 or version 1.0.1? In the first version there was a bug. Since the snowfall package was listed under Imports and not under Depends it was not loaded automatically. This should be fixed in version 1.0.1. If you are using 1.0.1 please let me know, so I can have a look at it again. If you use version 1.0.0, your error should disappear if you load snowfall manually before running the code.
